// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace web_api_demo.Models
{
    public partial class Blog
    {
        public Blog()
        {
           
        } 
        
        public int BlogId { get; set; }
        public string Url { get; set; } 
    }
}